FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

# Upgrade pip and force pure amd64 installs
RUN pip install --upgrade pip \
    && pip install --no-binary :all: --force-reinstall -r requirements.txt

COPY . .

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]